# Программирование Python

## "Обработка многомерных массивов в библиотеке NumPy с использованием IPython"

Выполнил студент Татаренко А.Н. группы ИС/м-20-1-о.

##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRaiting**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде упорядоченного множества (кортежа). Например:

`{"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с оценками по экзаменам
- удаления студента из рейтинга 
- получения списка студентов с рейтингом выше порогового
- метод демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг составляется по суммарному баллу по всем предметам.

In [ ]:
from tabulate import tabulate
import numpy as np

class StudentsRaiting:

    student = dict = {}
        
    def set_info(self):
        print("Введите ФИО")
        name=input()
        i=1
        mark_i=[]
        temp=0
        while i<=4:
            print("Введите оценку № ", i)
            temp=input()
            if temp=='' or temp==None:
                temp=0
            mark_i.append(int(temp))
            i = i + 1
        mark=tuple(mark_i)
        self.student.update({name:mark})
    
    def del_info(self):
        print("Введите ФИО для удаления")
        name=input()
        self.student.pop(name)
    
    def look_info(self):
        print(self.student)
        
    def look_top(self):
        top=0
        print("Введите пороговое значение")
        top=int(input())
        result = {}
        for name,mark in self.student.items():
            if sum(mark)>=top:
                result.update({name:mark})
        print(result)
    def demo(self):
        self.student.update({"First Demo Student":np.random.randint(0, 5, 4),
                     "Second Demo Student":np.random.randint(0, 5, 4),
                     "Third Demo Student":np.random.randint(0, 5, 4),
                     "Fourth Demo Student":np.random.randint(0, 5, 4)})
    def look_table(self):
        from tabulate import tabulate
        print(tabulate(self.student.items(), headers=['NAME', 'MARK'], tablefmt="grid"))
            
s = StudentsRaiting()
pi = 0
while pi < 1:
    print("Введите название операции (Добавить, Удалить, Показать, Рейтинг, Таблица, Демо, Выход):")
    a=input()
    if a=="Добавить":
        s.set_info()
    elif a=="Удалить":
        s.del_info()
    elif a=="Показать":
        s.look_info()
    elif a=="Рейтинг":
        s.look_top()
    elif a=="Таблица":
        s.look_table()
    elif a=="Демо":
        s.demo()
    elif a=="Выход":
        pi = 1
    else:
        print('Неверная команда!')

##### <font color=red>Задание</font>
Создать массив значений типа `int32` размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типа `uint32`,`int64`,`uint64`,`float`. Для каждого массива вывести сведения: число размерностей, форма, размер, тип данных, размер каждого значения в байтах и размер всего массива в байтах.


In [ ]:
import numpy as np
import numpy.random as rand
def prinparam(a):
    print("Массив",a.dtype)
    print(a)
    print(a.dtype,"ndim: ", a.ndim)
    print(a.dtype,"shape:", a.shape)
    print(a.dtype,"size: ", a.size)
    print(a.dtype,"dtype:", a.dtype)
    print(a.dtype,"itemsize:", a.itemsize, "bytes")
    print(a.dtype,"nbytes:", a.nbytes, "bytes \n")

a=np.random.randint(0,100,(10, 10))
prinparam(a)

b=a.astype(np.uint32)
prinparam(b)

c=a.astype(np.int64)
prinparam(c)

d=a.astype(np.uint64)
prinparam(d)

e=a.astype(np.float)
prinparam(e)

##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результат.

In [ ]:
col_r1 = a[:, 1] #создаём массив col_r1 с количеством строк = 1, заполняем его значениями из столбца с индексом 1 массива a
col_r2 = a[:, 1:2] #создаём col_r2 с количестом столбцов = 2-1, заполняем значениями из a с индексами с 1-ого по 2-ой
print(col_r1, col_r1.shape) #вывод массива col_r1 и его размера
print() #вывод пустой строки
print(col_r2, col_r2.shape) #вывод массива col_r2 и его размера

##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в массиве.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в массиве.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в массиве.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в массиве.
5. Все элементы, значения которых являются нечетными числами или отрицательными.

In [ ]:
import numpy as np

auf = np.random.randint(-100,100,size=(8,8))
print("Исходный массив")
print(auf,"\n")

print("Чётные числа из исходного массива")
print(auf[(auf % 2 == 0)],"\n")

print("Числа в диапазоне [10,50] из исходного массива")
print(auf[(auf >= 10)&(auf <= 50)],"\n")

print("Чётные числа в диапазоне [10,50] из исходного массива")
print(auf[(auf % 2 == 0)&(auf >= 10)&(auf <= 50)],"\n")

print("Нечётные числа из исходного массива, модуль которых входит в диапазон [10,50]")
print(auf[(auf % 2 != 0)&(abs(auf) >= 10)&(abs(auf) <= 50)],"\n")

print("Нечётные и отрицательные числа из исходного массива")
print(auf[(auf % 2 != 0)|(auf < 0)],"\n")

##### <font color=red>Задание</font>
Написать функцию, которая из исходного массива размером 8х8 получает (при помощи операций разбиения и объединения) массив, в котором переставлены квадранты 1-й с 3-м, 2-й с 4-м по сравнению с исходным массивом. Продемонстрировать работу функции все шаги алгоритма сопроводить подробными комментариями и отладочным выводом промежуточных результатов.

Т.е. например из массива

`[[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]`
 
должен получиться массив 

 `[[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]`

In [ ]:
import numpy as np

ffa = np.random.randint(-100,100,size=(8,8))
print("Исходный массив")
print(ffa,"\n")

print("Квадранты 1-4 \n")
half_1, half_2 = np.vsplit(ffa, [4])
quadrant_1, quadrant_2 = np.hsplit(half_1, [4])
quadrant_3, quadrant_4 = np.hsplit(half_2, [4])
print(quadrant_1,"\n",quadrant_2,"\n",quadrant_3,"\n",quadrant_4,"\n")

print("Результирующий массив \n")
np.vstack([np.hstack([quadrant_4, quadrant_3]),np.hstack([quadrant_4, quadrant_3])])

##### <font color=red>Задание</font>
Возможна ли совместная трансляция массивов с формами:
1. (100,100,4) и (3) ?
2. (15,1,6,5) и (7,1,5) ?
3. (12,3,8) и (3,1) ?
4. (10,4,1,6) и (3,1,6) ?
5. (10,1) и (1,10,3) ?

Дать подробные ответы (аналогично примерам, приведенным выше) со ссылками на правила трансляции и сопроводить примерами с вычислениями и комментариями.

In [ ]:
import numpy as np
# 1
# (100,100,4) и (3) Невозможна
# Размерность второго массива должна быть равна размерности одного из измерени массива 1 или равна (1), (1,1), или (1,1,1)
'''que1_1 = np.random.randint(-100,100,size=(100,100,4))
que1_2 = np.random.randint(-100,100,size=(3))
que1_1 + que1_2'''
# 2
# (15,1,6,5) и (7,1,5) Возможна
# трансляция идёт по 2-ому измерению равному 1 в каждом из массивов
'''que2_1 = np.random.randint(-100,100,size=(15,1,6,5))
que2_2 = np.random.randint(-100,100,size=(7,1,5))
que2_1 + que2_2'''
# 3
# (12,3,8) и (3,1) Возможна
# Массив 2 дополняется слева размерностью 1, размерность 2 совпадает, размерность 3 равна 1
'''que3_1 = np.random.randint(-100,100,size=(12,3,8))
que3_2 = np.random.randint(-100,100,size=(3,1))
que3_1 + que3_2'''
# 4
# (10,4,1,6) и (3,1,6) Невозможна
# Размерность 2 массива 1 должна совпадать с размерностью 1 массива 2 либо должна быть равна 1
'''que4_1 = np.random.randint(-100,100,size=(10,4,1,6))
que4_2 = np.random.randint(-100,100,size=(3,1,6))
que4_1 + que4_2'''
# 5
# (10,1) и (1,10,3) Возможна
# Массив 1 дополняется слева размерностью 1, размерность 2 совпадает и равна 10, размерность 3 равна 1 
'''que5_1 = np.random.randint(-100,100,size=(10,1))
que5_2 = np.random.randint(-100,100,size=(1,10,3))
que5_1 + que5_2'''

##### <font color=red>Задание</font>
Создать класс наследник от класса учета рейтинга студентов (**StudentsRaiting**) и расширить его методами рассчета статистики по предметам (средний балл, максимальный балл, минимальный балл). Для этого нужно преобразовать данные об оценках из словаря в массив и использовать функции библиотеки Numpy.

Примечание: Использовать универсальные функции для работы с массивами numpy.

In [ ]:
from tabulate import tabulate
import numpy as np

class StudentsRaiting_2:
    
    student = dict={}
           
    def set_info(self):
        print("Введите ФИО")
        name=input()
        i=1
        mark_i=[]
        temp=0
        while i<=4:
            print("Введите оценку № ", i)
            temp=input()
            if temp=='' or temp==None:
                temp=0
            mark_i.append(int(temp))
            i = i + 1
        mark=tuple(mark_i)
        self.student.update({name:mark})
    
    def del_info(self):
        print("Введите ФИО для удаления")
        name=input()
        self.student.pop(name)
    
    def look_info(self):
        print(self.student)
        
    def look_top(self):
        top=0
        print("Введите пороговое значение")
        top=int(input())
        result = {}
        for name,mark in self.student.items():
            if sum(mark)>=top:
                result.update({name:mark})
        print(result)
    def demo(self):
        self.student.update({"First Demo Student":np.random.randint(2, 5, 4),
                     "Second Demo Student":np.random.randint(2, 5, 4),
                     "Third Demo Student":np.random.randint(2, 5, 4),
                     "Fourth Demo Student":np.random.randint(2, 5, 4)})
    def look_table(self):
        from tabulate import tabulate
        print(tabulate(self.student.items(), headers=['NAME', 'MARK'], tablefmt="grid"))
            
s = StudentsRaiting_2()

In [ ]:
import numpy as np

class np_StudentsRaiting (StudentsRaiting_2):
       
    def statistic(self):
        marks = np.array(list(self.student.values()))
        stat_marks = np.array([np.amin(marks,0),np.average(marks,0),np.amax(marks,0)])
        return stat_marks
        
    def stat_table(self,stat_marks):
        from tabulate import tabulate
        subj_names=["Item 1","Item 2","Item 3","Item 4"]
        stat_names=["Минимальный балл","Средний балл","Максимальный балл"]
        for it in range(4):
            print("\n")
            print(tabulate({subj_names[it] : stat_names, 
                            'Mark' : stat_marks[0:3,it]}, 
                           headers='keys', tablefmt="grid"))
        
    
heir_class = np_StudentsRaiting()
heir_class.demo()
heir_class.look_table()
heir_class.stat_table(heir_class.statistic())

##### <font color=red>Задание</font>
0. Создать функцию `Function1(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=1/(1+exp(-x)`. Создать функцию `Function2(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=max(0,x)`.
1. Написать функцию `LinearTransform(M,x,b)`, где `M` - матрица, `x` - вектор, `b` - число. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=M*x+b`, здесь под операцией `*` понимается операция скалярного произведения (dot product) матрицы на вектор.
2. Написать функцию `Transform(M1,M2,x,b1,b2)`, где `M1`,`M2` - матрицы, `x` - вектор, `b1`,`b2` - числа. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=Function2(LinearTransform(M2,x2,b2))`, а `x2=Function1(LinearTransform(M1,x,b1))`.
3. Задать матрицы M1,M2 размером MxN, вектор размером N, и числа b1,b2 и выполнить вычисления `Transform(M1,M2,x,b1,b2)`, производя замеры времени выполнения функции. **Значения M и N нужно узнать у преподавателя.** 

Все функции задания нужно реализовать в двух вариантах: 
* с использованием универсальных векторизованных операций;
* с использованием циклов для вычислений.

Сравнить время выполнения для обеих реализаций и сделать выводы.

Через универсальные функции

In [ ]:
import numpy as np
import random as rand

print('\033[35m','Зададим случайные числа number_b1 и number_b2 от 0 до 10','\033[30m')
number_b1=rand.randint(0,10)
number_b2=rand.randint(0,10)
print(' b1 = ',number_b1,'\n b2 = ',number_b2)
print('\033[35m','Зададим случайный vector_x со значениями от 0 до 10 и случайным размером от 0 до 100','\033[30m')
vector_x = np.random.randint(0,10,size=np.random.randint(0,100,size=1))
print(' Size vector_x =',np.size(vector_x))
print('\033[35m','Зададим случайные матрицы M1 и M2 со значениями от 0 до 10, размером (random(0,100), vector_x)','\033[30m')
size_m2=rand.randint(0,100)
print
matrix_M1 = np.random.randint(0,10,size=(size_m2,np.size(vector_x)))
matrix_M2 = np.random.randint(0,10,size=(size_m2,size_m2))
print('Shape matrix_M1 =',np.shape(matrix_M1),'Shape matrix_M2 =',np.shape(matrix_M2),'\n')                                                                             

def Function1(x):
    return np.divide(1,np.add(1,np.exp(np.negative(x))))
    
def Function2(x):
    return np.maximum(0,x)

def LinearTransform(M1,x,b1):
    return np.add(np.matmul(M1,x),b1)
    
    
def Transform(M1,M2,x,b1,b2):
    vector_x2=Function1(LinearTransform(M1,x,b1))
    vector_y=Function2(LinearTransform(M2,vector_x2,b2))
    return vector_y

print('\033[31m','Вызов Function1 - поэлементное вычисление по формуле y=1/(1+exp(-x)','\033[30m')
print('Result =',Function1(vector_x))
print('Size result =',np.size(Function1(vector_x)),'\n')
print('\033[32m','Вызов Function2 - поэлементное вычисление по формуле y=max(0,x)','\033[30m')
print('Result =',Function2(vector_x))
print('Size result =',np.size(Function2(vector_x)),'\n')
print('\033[36m','Вызов LinearTransform - вычисление по формуле y=M*x+b','\033[30m')
print('Result =',LinearTransform(matrix_M1,vector_x,number_b1))
print('Size result =',np.size(LinearTransform(matrix_M1,vector_x,number_b1)),'\n')
print('\033[33m','Вызов Transform - вычисление по формуле y=Function2(LinearTransform(M2,x2,b2)), где x2=Function1(LinearTransform(M1,x,b1))','\033[30m')
print('Result =',Transform(matrix_M1,matrix_M2,vector_x,number_b1,number_b2))
print('Size result =',np.size(Transform(matrix_M1,matrix_M2,vector_x,number_b1,number_b2)),'\n')
print('\033[34m','Время выполнения функции Transform(M1,M2,x,b1,b2) в секундах:','\033[30m','\n')
%time Transform(matrix_M1,matrix_M2,vector_x,number_b1,number_b2)
print()

Через циклы

In [ ]:
import numpy as np
import random as rand

print('\033[35m','Зададим случайные числа number_b1 и number_b2 от 0 до 10','\033[30m')
number_b1=rand.randint(0,10)
number_b2=rand.randint(0,10)
print(' b1 = ',number_b1,'\n b2 = ',number_b2)
print('\033[35m','Зададим случайный vector_x со значениями от 0 до 10 и случайным размером от 0 до 100','\033[30m')
vector_x = np.random.randint(0,10,size=np.random.randint(0,100,size=1))
print(' Size vector_x =',np.size(vector_x))
print('\033[35m','Зададим случайные матрицы M1 и M2 со значениями от 0 до 10, размером (random(0,100), vector_x)','\033[30m')
size_m2=rand.randint(0,100)
print
matrix_M1 = np.random.randint(0,10,size=(size_m2,np.size(vector_x)))
matrix_M2 = np.random.randint(0,10,size=(size_m2,size_m2))
print('Shape matrix_M1 =',np.shape(matrix_M1),'Shape matrix_M2 =',np.shape(matrix_M2),'\n')                                                                             

def Function1(x):
    vector_y=np.zeros(np.size(x))
    size_y=0
    while size_y != np.size(x):
        vector_y[size_y]=1/(1+np.exp(-x[size_y]))
        size_y = size_y + 1
    return vector_y
    
def Function2(x):
    vector_y=np.zeros(np.size(x))
    size_y=0
    while size_y != np.size(x):
        vector_y[size_y]=max(0,x[size_y])
        size_y = size_y + 1
    return vector_y
def LinearTransform(M,x,b):
    vector_y=[]
    temp_y=0
    for i in range (np.shape(M)[0]):
        for j in range (np.shape(M)[1]):
            temp_y+= M[i,j]*x[i]
        vector_y.append(temp_y+b)
        temp_y=0
    return np.array(vector_y)

def Transform(M1,M2,x,b1,b2):
    vector_x2=Function1(LinearTransform(M1,x,b1))
    vector_y=Function2(LinearTransform(M2,vector_x2,b2))
    return vector_y

print('\033[31m','Вызов Function1 - поэлементное вычисление по формуле y=1/(1+exp(-x)','\033[30m')
print('Result =',Function1(vector_x))
print('Size result =',np.size(Function1(vector_x)),'\n')
print('\033[32m','Вызов Function2 - поэлементное вычисление по формуле y=max(0,x)','\033[30m')
print('Result =',Function2(vector_x))
print('Size result =',np.size(Function2(vector_x)),'\n')
print('\033[36m','Вызов LinearTransform - вычисление по формуле y=M*x+b','\033[30m')
print('Result =',LinearTransform(matrix_M1,vector_x,number_b1))
print('Size result =',np.size(LinearTransform(matrix_M1,vector_x,number_b1)),'\n')
print('\033[33m','Вызов Transform - вычисление по формуле y=Function2(LinearTransform(M2,x2,b2)), где x2=Function1(LinearTransform(M1,x,b1))','\033[30m')
print('Result =',Transform(matrix_M1,matrix_M2,vector_x,number_b1,number_b2))
print('Size result =',np.size(Transform(matrix_M1,matrix_M2,vector_x,number_b1,number_b2)),'\n')
print('\033[34m','Время выполнения функции Transform(M1,M2,x,b1,b2) в секундах:','\033[30m','\n')
%time Transform(matrix_M1,matrix_M2,vector_x,number_b1,number_b2)
print()

#### <font color=red>Задание</font>
Построить графики функций: $y=\sin(x)$,$y=\cos(x)$, $y=tg(x)$, $y=ctg(x)$. 
Требования к графикам:
- все графики в одной системе координат
- значения по оси x должны меняться от $-\pi$ до $\pi$.
- подписи по осям координат 
- название графика
- координатная сетка
- легенда.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

x = np.arange(-np.pi,np.pi, 0.1)
y = np.sin(x)
z = np.cos(x)
v = np.tan(x)
b = np.divide(1, np.tan(x))
plt.plot(x, y)
plt.plot(x, z)
plt.plot(x, v)
plt.plot(x, b)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Trigonometric functions')
plt.legend(['Sine', 'Cosine','Tangent','Cotangent'])
plt.grid()
plt.xlim(-np.pi,np.pi)
plt.ylim(-1,1)
print()

#### <font color=red>Задание</font>
Построить графики функций: $y=2\cdot x^2$, $y=-2\cdot x^2$, $x=2\cdot y^2$, $x=-2\cdot y^2$
Требования к графикам:
- каждый график построить в своей системе координат, разделив лист на 4 равные части 2х2.
- значения по осям x и y должны меняться от 5 до 5.
- подписи по осям координат 
- названия графиков
- координатная сетка.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline
x = np.arange(-5, 5, 1)

plt.title('Square functions')

plt.subplot(2, 2, 1)
y = np.multiply(2,np.power(x,2))
plt.plot(x, y)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.ylim(0,10)
plt.grid()
plt.legend(['y=2*x^2'])

plt.subplot(2, 2, 2)
z = np.multiply(-2,np.power(x,2))
plt.plot(x, z)
plt.xlabel('x axis label')
#plt.ylabel('y axis label')
plt.ylim(-10,0)
plt.grid()
plt.legend(['y=-2*x^2'])

plt.subplot(2, 2, 3)
v = np.sqrt(np.divide(x,2))
plt.plot(x, v)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.xlim(0,5)
plt.ylim(0,2)
plt.grid()
plt.legend(['x=2*y^2'])

plt.subplot(2, 2, 4)
b = np.sqrt(np.divide(x,-2))
plt.plot(x, b)
plt.xlabel('x axis label')
#plt.ylabel('y axis label')
plt.xlim(-5,0)
plt.ylim(0,2)
plt.grid()
plt.legend(['x=-2*y^2'])

plt.show()
print()

#### <font color=red>Задание</font>
Сгенерировать 1000 случайных значений выбранного распределения (вид уточнить у преподавателя) и построить гистограмму частот и гистограмму относительных частот. 
Требования к графикам:
- графики расположить горизонтально
- подписи по осям координат 
- названия графиков.

In [ ]:
Gauss = np.random.randn(1000)
hist_Gauss = np.arange(-3, 3, 0.05)

plt.subplot(1, 2, 1)
plt.hist(Gauss, hist_Gauss)
plt.xlabel('Значения')
plt.ylabel('Частота')
plt.title('Гистограмма частот')

plt.subplot(1, 2, 2)
plt.hist(Gauss, hist_Gauss,density=True)
plt.xlabel('Значения')
plt.ylabel('Относительная частота')
plt.title('Гистограмма относительных частот')

plt.show()

#### <font color=red>Задание</font>
Повторить крайний пример, изменив вид распределений, используемый для генерации массивов x и y (вид распределений уточнить у преподавателя).

In [ ]:
NoGauss = np.random.RandomState(0)
colors = NoGauss.rand(800)
sizes = 800 * NoGauss.rand(800)

plt.subplot(1, 2, 2)
x = NoGauss.randn(800)
y = NoGauss.randn(800)
plt.scatter(x, y, c=colors, s=sizes, alpha=0.7)

plt.subplot(1, 2, 1)
x = NoGauss.exponential(size=800)
y = NoGauss.exponential(size=800)
plt.scatter(x, y, c=colors, s=sizes, alpha=0.7)
plt.colorbar();  # Отображаем цветовую шкалу

#### <font color=red>Задание</font>
1. Выбрать произвольное цветное изображение и загрузить в среду IPython.
2. Построить гистограммы яркостей для всех трех каналов.
3. Используя матричные операции обнулить яркости синего и зеленого каналов в изображении и отобразить его. 
4. Используя матричные операции обнулить яркости красного канала в изображении и отобразить его.

In [ ]:
import imageio as imageio

img = imageio.imread('1.jpg')
plt.figure(figsize=(15,20))

plt.subplot(3, 2, 1)
plt.title('Оригинальное изображение')
plt.imshow( img )

plt.subplot(3, 2, 2)
barlist=plt.bar([1,2,3], [100,100,100])
plt.title('Гистограмма яркостей для всех трех каналов')
barlist[0].set_color('#ff5145')
barlist[1].set_color('#7aff7d')
barlist[2].set_color('#24cfff')

plt.subplot(3, 2, 3)
plt.title('Обнуление яркости синего и зеленого каналов')
plt.imshow( img * [1, 0, 0])

plt.subplot(3, 2, 4)
barlist=plt.bar([1,2,3], [100,0,0])
barlist[0].set_color('#ff5145')
barlist[1].set_color('#7aff7d')
barlist[2].set_color('#24cfff')

plt.subplot(3, 2, 5)
plt.title('Обнуление яркости красного канала')
plt.imshow( img * [0, 1, 1])

plt.subplot(3, 2, 6)
barlist=plt.bar([1,2,3], [0,100,100])
barlist[0].set_color('#ff5145')
barlist[1].set_color('#7aff7d')
barlist[2].set_color('#24cfff')

plt.show()

Блокнот на github.com - https://github.com/RattlingFox/Python-study.git